
from ..rcemp.model import RCEMPModel
from .agents import DialRegulatorAgent
from .env import DialEnv


class RCEMPDIALModel(RCEMPModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL'
    REGULATOR_CLASS = DialRegulatorAgent
    ENV_CLASS = DialEnv
    PRODUCER_DISPATCH_RULE = 'WFIFO'
    MAINTENER_DISPATCH_RULE = 'WFIFO'


class RCEMPDIALModel1(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-p-FIFO'
    PRODUCER_DISPATCH_RULE = 'FIFO'
    
class RCEMPDIALModel2(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-p-EDD'
    PRODUCER_DISPATCH_RULE = 'EDD'
    
    
class RCEMPDIALModel3(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-m-FIFO'
    MAINTENER_DISPATCH_RULE = 'FIFO'
    
class RCEMPDIALModel4(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-m-EDD'
    MAINTENER_DISPATCH_RULE = 'EDD'


class RCEMPDIALModel5(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-p-RANDOM'
    PRODUCER_DISPATCH_RULE = 'RANDOM'

class RCEMPDIALModel6(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-p-RANDOM-EDD'
    PRODUCER_DISPATCH_RULE = 'RANDOM-EDD'

class RCEMPDIALModel7(RCEMPDIALModel):    
    ALGORITHM_NAME = 'RCEMP-DIAL-m-RANDOM'
    MAINTENER_DISPATCH_RULE = 'RANDOM'

    